### ISSUE TITLE
Cannot use childviewflyout ui component

### ISSUE THREAD

**Issue by rootasjey** [gleborgne/winjscontrib#5]
Hello,

I tried to use the childviewflyout ui component in my Windows Phone 8.1 app like this:

**default.html**

``` js
<script src="Scripts/jquery-2.1.4.js"></script>
<script src="/Scripts/winjscontrib/winjscontrib.ui.navigator.js"></script>
<script src="/Scripts/winjscontrib/winjscontrib.ui.childviewflyout.js"></script>
<link href="/css/winjscontrib/winjscontrib.ui.childviewflyout.css" rel="stylesheet" />
```

**An HTML page**

``` html
<!-- Flyout -->
<div id="childview" data-win-control="WinJSContrib.UI.ChildViewFlyout"></div>
```

**A JavaScript page binded to the html page above**

``` js
var childview = element.querySelector('#childview').winControl;
childview.open('/pages/commits/commits.html');
```

But I get this following error:

``` js
"TypeError: Object doesn't support property or method 'tap'
  at _createContent (ms-appx://17924jrmiecorpinot.octopull/Scripts/winjscontrib/winjscontrib.ui.childviewflyout.js:71:20)
  at Anonymous function (ms-appx://17924jrmiecorpinot.octopull/Scripts/winjscontrib/winjscontrib.ui.childviewflyout.js:54:16)
  at activate2 (ms-appx://17924jrmiecorpinot.octopull/WinJS/js/base.js:9546:17)
   at Promise_ctor (ms-appx://17924jrmiecorpinot.octopull/WinJS/js/base.js:2566:17)
   at activate (ms-appx://17924jrmiecorpinot.octopull/WinJS/js/base.js:9518:9)\n   at processAllImpl2 (ms-appx://17924jrmiecorpinot.octopull/WinJS/js/base.js:9613:21)
   at Promise_ctor (ms-appx://17924jrmiecorpinot.octopull/WinJS/js/base.js:2566:17)
   at processAllImpl (ms-appx://17924jrmiecorpinot.octopull/WinJS/js/base.js:9557:9)
   at processAll (ms-appx://17924jrmiecorpinot.octopull/WinJS/js/base.js:9673:13)
   at process (ms-appx://17924jrmiecorpinot.octopull/WinJS/js/base.js:26320:13)"
```

Do you have any idea?
Thanks.

**Comment by gleborgne** [comment]
You need to add winjscontrib.core to make it work.

**Comment by rootasjey** [comment]
Thank you for your quick answer.

I added winjscontrib.core to my **default.html** page just after the _jquery_ script tag:

``` js
<script src="Scripts/jquery-2.1.4.js"></script>
<script src="Scripts/winjscontrib/winjscontrib.core.js"></script>
```

But I've still the same error message. I'll try to see if it works with the updated sources from GitHub, since I got mine from NuGet Package Manager.

**Comment by gleborgne** [comment]
The nuget version is a bit outdated. I must take time to publish new versions for it. With the version on nuget, you may have to add a few other libs (wibjscontrib.jquery and winjscontrib.animation). I advice you to take the version in the dist folder from github

**Comment by rootasjey** [comment]
I managed to get it work with the GitHub sources :D
Thank you for your help!

**Comment by gleborgne** [comment]
Feel free to ask for help, or provide feedback if you experience any friction

**Comment by rootasjey** [comment]
Thanks! I'll try to write a little blog post tomorrow for anyone experiencing this issue :)
